### ISSUE TITLE
User-Dashboard: Product (Add new Product)

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#19] opened 2022-10-03 14:24 UTC
- Develop the User Dashboard add new product pages UI appropriately
- The user dashboard upload product page contains 4 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by ScottDeev** [comment] 2022-10-04 14:54
And for the page 2 and page 3 of the 'Add new Product' design are the same, making it 3 pages to be designed instead of 4

**Comment by ScottDeev** [comment] 2022-10-08 10:26
![Screenshot (233)](https://user-images.githubusercontent.com/99127718/194702958-0c4d8b9b-0dd2-4e9e-885e-54981d13a055.png)

**Comment by ScottDeev** [comment] 2022-10-08 12:42
![Screenshot (234)](https://user-images.githubusercontent.com/99127718/194708136-635ab714-95ad-4b5f-abdd-23f6da10949b.png)
![Screenshot (235)](https://user-images.githubusercontent.com/99127718/194708140-1dc22021-463f-458d-8342-d3fedd0a3644.png)
![Screenshot (236)](https://user-images.githubusercontent.com/99127718/194708148-1f61f98c-ceb7-49d2-b083-caed2cfc5d0c.png)

**Comment by ScottDeev** [comment] 2022-10-08 12:43
All the tasks has been implemented. They was a duplicate of pages on the figma design so it was three pages and not four for this section

**Closed** 2022-10-09 16:07 UTC
Labels: UI, hacktoberfest-accepted, hacktoberfest
