### ISSUE TITLE
Develop the Forgot Password page

### ISSUE THREAD

**Issue by Basit46** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#74] opened 2022-10-07 10:36 UTC
Title
-----

Development of the Forgot Password page

**Comment by t-bello7** [comment] 2022-10-07 10:42
This a duplicate of #10

**Comment by Basit46** [comment] 2022-10-07 10:45
God Abeg 
You can Close it bro.

**Comment by t-bello7** [comment] 2022-10-07 10:48
Try and look at the issues created first. If no one has been assigned then you can assign and work on it. Have assigned #66 to you though. I closed #65 cause someone said he has finished working on it on the channel.

**Closed by t-bello7** 2022-10-07 10:48 UTC
Labels: hacktoberfest-accepted, hacktoberfest
