### ISSUE TITLE
Navbar and Hero Component of Landing Page

### ISSUE THREAD

**Issue by Basit46** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#65] opened 2022-10-06 16:43 UTC
Title
-----

Develop  the Navbar and Hero page

Summary
-------

I want to start by developing the Navbar and Hero page and make it fully responsive

Environment
-----------

[environment of where the issue occrs; e.g., operating system version, browser version, and so on]

Steps to reproduce
------------------

1. Create components for the sections.
2. Link them up
3. Make it responsive

Expected result
---------------

A landing page then we can proceed with other pages.

**Comment by t-bello7** [comment] 2022-10-06 20:10
@Basit46  Can you break this issue into sub-tasks by breaking the page development into components like navbar, main, footer, e.t.c

**Comment by Basit46** [comment] 2022-10-06 20:15
@t-bello7 Ok then, I will focus on the Navbar and Hero page.

**Comment by t-bello7** [comment] 2022-10-06 20:50
Alright, that's cool. I changed the issue name so other devs can work on the remaining components and create issues for them.

**Comment by t-bello7** [comment] 2022-10-07 09:57
Duplicate of #2. Hello @Basit46 is it Okay to close this issue? I apologize if you have gone far in working on it.

**Comment by Basit46** [comment] 2022-10-07 10:00
@t-bello7 You mean I should stop working on it? What came up?

**Closed** 2022-10-07 10:34 UTC
Labels: hacktoberfest-accepted, hacktoberfest
